name: Deploy Java App to Azure Web App

on:
  push:
    branches:
      - master  # Cambia esta rama según tus necesidades

env:
  AZURE_WEBAPP_NAME: 'taskManager'  # Nombre de tu App Service en Azure
  AZURE_WEBAPP_PACKAGE_PATH: 'target/*.jar'  # Ruta del archivo JAR después del build
  JAVA_VERSION: '21'  # Versión de Java que estás utilizando

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout your code
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    # 2. Set up Java
    - name: 'Set up JDK ${{ env.JAVA_VERSION }}'
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'  # O 'zulu' si prefieres

    # 3. Build the project using Maven
    - name: 'Build with Maven'
      run: mvn clean package

    # 4. Deploy the JAR file to Azure Web App
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}  # Nombre de tu App Service
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Configura el secret en GitHub
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}  # Ruta del archivo JAR generado

